; Exercise 2.52
; Author: Evan Ezell

(define wave-smile-painter
  (let ((segment-list (list (make-segment (make-vect 0.50 0.40)
                                          (make-vect 0.60 0.00))
                            (make-segment (make-vect 0.50 0.40)
                                          (make-vect 0.40 0.00))
                            (make-segment (make-vect 0.30 0.00)
                                          (make-vect 0.35 0.65))
                            (make-segment (make-vect 0.35 0.65)
                                          (make-vect 0.15 0.55))
                            (make-segment (make-vect 0.15 0.55)
                                          (make-vect 0.00 0.80))
                            (make-segment (make-vect 0.00 0.90)
                                          (make-vect 0.20 0.70))
                            (make-segment (make-vect 0.20 0.70)
                                          (make-vect 0.30 0.75))
                            (make-segment (make-vect 0.30 0.75)
                                          (make-vect 0.40 0.75))
                            (make-segment (make-vect 0.40 0.75)
                                          (make-vect 0.35 0.90))
                            (make-segment (make-vect 0.35 0.90)
                                          (make-vect 0.40 1.00))
                            (make-segment (make-vect 0.55 1.00)
                                          (make-vect 0.60 0.90))
                            (make-segment (make-vect 0.60 0.90)
                                          (make-vect 0.55 0.75))
                            (make-segment (make-vect 0.55 0.75)
                                          (make-vect 0.65 0.75))
                            (make-segment (make-vect 0.65 0.75)
                                          (make-vect 1.00 0.45))
                            (make-segment (make-vect 1.00 0.30)
                                          (make-vect 0.60 0.65))
                            (make-segment (make-vect 0.60 0.65)
                                          (make-vect 0.70 0.00))
                            (make-segment (make-vect 0.46 0.80)
                                          (make-vect 0.50 0.80))
                            (make-segment (make-vect 0.44 0.90)
                                          (make-vect 0.45 0.90))
                            (make-segment (make-vect 0.51 0.90)
                                          (make-vect 0.52 0.90))))) 
    (segments->painter segment-list)))

(define (corner-split painter n)
  (if (= n 0)
      painter
      (let ((up (up-split painter (- n 1)))
            (right (right-split painter (- n 1))))
        (let ((top-left (beside up x-painter))
              (bottom-right (below diamond-painter right))
              (corner (corner-split painter (- n 1))))
          (beside (below painter top-left)
                  (below bottom-right corner))))))

(define (square-limit painter n)
  (let ((combine4 (square-of-four flip-horiz rotate-180
                                  rotate-180 flip-vert)))
    (combine4 (corner-split painter n))))
