;;; Exercise 3.4 
;;; Author: Evan Ezell

(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      (error "Insufficient funds")))
  (define (deposit amount)
    (begin (set! balance (+ balance amount))
           balance))
  (define (call-the-cops) (error "call the cops"))
  (let ((fails 0))
    (define (dispatch psswd m)
      (if (not (eq? password psswd))
        (begin (set! fails (+ fails 1))
               (if (= fails 7)
                 (call-the-cops)
                 (lambda (amount) (error "Incorrect password"))))
        (begin (set! fails 0)
               (cond ((eq? m 'withdraw) withdraw)
                     ((eq? m 'deposit) deposit)
                     (else (error "Unknown request -- MAKE-ACCOUNT" m))))))
      dispatch))
